'use strict'

// Hand-written public wrapper. The heavy lifting lives in the native primitive
// (binding.js, generated by @napi-rs/cli). This layer adds the builder API and the
// error-class hierarchy, mirroring the Ruby binding (pure-Ruby builder over a single
// native `render` primitive).
const binding = require('./binding.js')

// --- error hierarchy (mirrors Ruby/Python: StrictError is a ParseError subclass) ---

class FulgurParseError extends Error {
  constructor(message) {
    super(message)
    this.name = 'FulgurParseError'
  }
}

class FulgurStrictError extends FulgurParseError {
  constructor(message) {
    super(message)
    this.name = 'FulgurStrictError'
  }
}

class FulgurRenderError extends Error {
  constructor(message) {
    super(message)
    this.name = 'FulgurRenderError'
  }
}

// Map the native discriminant `code` -> error class (mechanical; no message parsing).
function makeError(code, message) {
  switch (code) {
    case 'STRICT_ERROR':
      return new FulgurStrictError(message)
    case 'RENDER_ERROR':
      return new FulgurRenderError(message)
    default: // 'PARSE_ERROR'
      return new FulgurParseError(message)
  }
}

// --- low-level render primitive (the builder calls this; also callable directly) ---

function render(specJson, format, options) {
  // Coerce the format to a string before crossing the native boundary (mirrors the Ruby
  // binding's `to_s`): non-string values like null/false become "null"/"false", which the
  // native layer rejects as an unsupported format (ParseError) rather than throwing a raw
  // napi type-conversion error. The Builder resolves `undefined` to a fallback first.
  const r = binding.render(specJson, String(format), options ?? {})
  if (!r.ok) {
    throw makeError(r.code, r.message)
  }
  // Exactly one of svg/png/webp is set on success; png/webp are Buffers. `!= null` covers
  // both null and undefined.
  return r.svg != null ? r.svg : (r.png != null ? r.png : r.webp)
}

// --- fluent, reusable builder (setters mutate and return `this`) ---

class Builder {
  constructor(specJson) {
    this._spec = specJson
    this._opts = {}
  }

  width(value) {
    this._opts.width = value
    return this
  }

  height(value) {
    this._opts.height = value
    return this
  }

  scale(value) {
    this._opts.scale = value
    return this
  }

  dsl(value) {
    this._opts.dsl = value
    return this
  }

  font(bytes) {
    this._opts.font = bytes
    return this
  }

  strict(value = true) {
    this._opts.strict = value
    return this
  }

  format(value) {
    this._opts.format = value
    return this
  }

  // Format precedence: explicit argument > .format() setter > default 'svg'.
  // Only a truly unset setter falls back: an explicitly stored format (even null/false) is
  // forwarded to the native layer, which rejects an invalid value as ParseError. Presence is
  // tested with `in` (not `??`) so `.format(null).render()` matches `render(null)` — and the
  // Ruby binding's `@opts.key?(:format)` semantics — rather than silently rendering svg.
  render(format) {
    const resolved =
      format !== undefined ? format : 'format' in this._opts ? this._opts.format : 'svg'
    const { format: _ignored, ...rest } = this._opts
    return render(this._spec, resolved, rest)
  }
}

function build(specJson) {
  return new Builder(specJson)
}

function schema(dsl) {
  // Coerce to a string before the native boundary (like render): non-string values become
  // e.g. "null" and are rejected as an unsupported DSL (FulgurParseError) instead of throwing
  // a raw napi conversion error — preserving the native layer's never-throw contract.
  const r = binding.schema(String(dsl))
  if (!r.ok) {
    throw makeError(r.code, r.message)
  }
  return r.value
}

function version() {
  return binding.version()
}

module.exports = {
  build,
  render,
  schema,
  version,
  FulgurParseError,
  FulgurStrictError,
  FulgurRenderError,
}
